server:
  port: 8087

spring:
  application:
    name: notification-service
  mail:
    host: ${MAIL_HOST:smtp.gmail.com}
    port: ${MAIL_PORT:587}
    username: ${MAIL_USERNAME:noreply.zestmarket@gmail.com}
    password: ${MAIL_PASSWORD:secret}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  kafka:
    bootstrap-servers: ${KAFKA_HOST:localhost}:9092
    consumer:
      group-id: notification-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

eureka:
  client:
    serviceUrl:
      defaultZone: http://${EUREKA_HOST:localhost}:8761/eureka/

springdoc:
  servers:
    - url: http://localhost:8080
      description: API Gateway
    - url: http://localhost:8087
      description: Direct Notification Service

